eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  zipkin:
    base-url: http://localhost:7082/
server:
  port: 7075